# Introduction

Data Science has ranked as one of the most in-demand jobs in Australia in recent consecutive years. As demands steadily grows, students are also increasingly interested in Data Science degrees, yet recruiters still seem to struggle to fill up data science positions. This leads to our main question: what is Data Science? Is there a shared structure or skill set of Data Science courses offered at Australian universities? Are students and employers' perception of data science similar? To answer these questions, we looked at data from both University and Employer perspectives. 

There is no readily available data from Australian universities, so we had to collect our own data set through web scraping. The initial target was to collect data from all universities in Australia including both undergraduate and postgraduate courses, however, due to time constrain, the data collected for this project only contains Master of Data Science courses from the Group of Eight (Go8) universities. The data on job description (which we refer to as "employer data") was retrieved from [Data Scientist Job Listings]((https://www.kaggle.com/code/nomilk/exploring-2-years-of-data-scientist-job-listings/data)) on Kaggle. 

By exploring the current situation and potentially a definition of Data Science in Australia from both the university and employer perspectives, the findings would help students and recruiters have a clearer picture of what to expect, as well as raising attentions and awareness to potential gaps between employer demands and university offerings.


[ET: write how the remaining sections are structured here.]