# Conclusion {#sec-conclude}

## Summary 

In this project, we collected university data and employer data to conduct analysis. For the university data, we used web scraping techniques to build our data set from scratch. Then, in depth exploratory data analysis was conducted. Finally, to try and solve problems we encountered during the analysis, we built LDA models through web scraping over 4000 Wikipedia articles to establish our own 'text corpus'

From the exploratory data analysis, we find that Master of Data Science degrees offered at Go8 are mostly dominated by **computational component**, even the statistical aspects of it are more computational. There is no obvious standard structure or skill set for data science degrees across Go8. Hence we fail to give a definite answer on what is universities' definition of data science in Australia. The employer's data offered us insight to the type of programming languages are favored by employers. We find that Python, R and SQL are the dominating ones. Data visualization is an important skill from employers' perspective since it appears frequently in @fig-employer-bigram and Tableau is quite popular in @fig-languages.
  
Through the application of LDA model, trained with only statistical data, we saw the breakdown of topics for employers and for universities are slightly different. However, we lack the data and tools to measure if the difference is significant.  
  
## Limitation

The research has a few limitations. The lack of data consistency within Go8 universities lead to the small data size which made it difficult to measure the significance the analysis. Without information on programming languages taught at universities, we were not able to draw direct comparison with employers.

We assumed the nature of units (computational, statistical..etc.) based on the unit code when in reality the unit code is not a definite measure of the content being taught. Our assumption that the content is implied by unit code may be wrong.

A proper text corpus requires great understanding of linguistics and a large amount of articles. The result of our LDA model topic breakdown can also simply be due to the fact that only a few of the wiki-articles we used are relevant and therefore will consistently be significant for employer and university data.

We relied heavily on packages like `tidytext` and `SnowballC` for word processing. However, there still are some drawbacks. The stemmed words are still potentially not "clean" enough and produce misleading results.

## Furture Directions

To continue this project in the future, more degrees (e.g. Business Analytics) from other Australian Universities can be added to the university data set. Also, more thought can be put into the employer data collection. A different approach to obtaining employer data can be considered so that the two data set is more comparable. Considering Business analyst, data scientist, and data engineer positions. Should these positions be put into one data set? Last but not least, more experiments should be done with the LDA model. Such as, using different weights for the model parameters. Other articles can also be used to train the model. Other methodologies to convert text data into numerical data (eg. word2vec) can also be experimented.