project:
  type: book

book:
  title: "dsreport"
  author: "Xinrui WANG and Tsai-Chun TSOU"
  date: "`r Sys.Date()`"
  chapters:
    - index.qmd
    - "01-intro.qmd"
    - "02-data.qmd"
    - "02-1-datascraping.qmd"
    - "03-methods.qmd"
    - "04-textanalysis.qmd"
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



