project:
  type: book

book:
  title: "Defining Data Science"
  subtitle: "A Case Study in Australia"
  author: "Xinrui WANG and Tsai-Chun TSOU"
  date: "`r Sys.Date()`"
  search: true
  downloads: [pdf]
  repo-url: https://github.com/numbats/ds-report
  repo-actions: [source]
  chapters:
    - index.qmd
    
    - "01-abstract.qmd"
    - "02-intro.qmd"
    
    -  "03-data.qmd"
    
    - part: "04-textanalysis.qmd"
      chapters:
         - "04_1-unitext.qmd"
         - "04_2-jobtext.qmd"
    
    - part: "05-text2vec.qmd"
      chapters:
         - "05_1-unilda.qmd"
         - "05_2-joblda.qmd"
    
    - part: "Conclusion"
      chapters:
         - "06_1-limitation.qmd"
         - "06_2-conclusion.qmd"
         
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: 
        light: flatly
        dark: darkly
  pdf:
    documentclass: scrreprt
