# Abstract {.unnumbered}

Universities are increasingly offering degrees that specialise in the so-called "Data Science" but what is Data Science and what skill are students expected to master in these degrees? The Australian Mathematical Sciences Institute (AMSI) and the Statistical Society of Australia (SSA) are conducting a review of role of of Data Science in Australia universities using   [surveys](https://amsi.org.au/amsi-ssa-data-science-review/) and focus groups. Our research attempts to tackle this topic by using data available from public resources. More specifically, we collected unit description and learning objectives/outcomes in Master of Data Science in the Group of Eight (Go8) Universities and job description of data scientist roles from seek.com.au available on from [Kaggle](https://www.kaggle.com/code/nomilk/exploring-2-years-of-data-scientist-job-listings/data). We used the data to decompose the core disciplines involved in the degree as well the type of skill sets that may be required. To expand on the initial exploratory data analysis, we also build Latent Dirichlet Allocation models to construct our own text corpus.

From the exploratory data analysis, we observe a lack of homogeneity of the composition of unit structure across the Go8 universities. The inconsistent data metrics made it difficult to draw direct comparison between the employer data and university data. Nonetheless we were able to conclude that computational components are more prominent in data science for both the university and employer perspectives.